- testcase: "[TC-PCC-1.1] Global attributes with server as DUT"
  commands:
    - command: "./chip-tool pumpconfigurationandcontrol read cluster-revision 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read feature-map 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read attribute-list 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read accepted-command-list 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read generated-command-list 1 1"
      logs:
        - " "
- testcase: "[TC-PCC-2.1] Attributes with server as DUT"
  commands:
    - command: "./chip-tool pumpconfigurationandcontrol read max-pressure 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-speed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-flow 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read min-const-pressure 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-const-pressure 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read min-comp-pressure 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-comp-pressure 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read min-const-speed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-const-speed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read min-const-flow 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-const-flow 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read min-const-temp 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read max-const-temp 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read pump-status 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-operation-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read capacity 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read speed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-running-hours 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read power 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-energy-consumed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read operation-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read control-mode 1 1"
      logs:
        - " "
- testcase: "[TC-PCC-2.2] Primary functionality with server as DUT"
  commands:
    - command: "./chip-tool pumpconfigurationandcontrol write operation-mode 0 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-operation-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write operation-mode 1 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-operation-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write operation-mode 2 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-operation-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write operation-mode 3 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-operation-mode 1 1"
      logs:
        - " "
- testcase: "[TC-PCC-2.3] Primary functionality with server as DUT"
  commands:
    - command: "./chip-tool pumpconfigurationandcontrol write operation-mode 0 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-operation-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write control-mode 0 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write control-mode 1 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write control-mode 2 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write control-mode 3 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write control-mode 5 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write control-mode 7 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read effective-control-mode 1 1"
      logs:
        - " "
- testcase: "[TC-PCC-2.4] Primary functionality with server as DUT"
  commands:
    - command: "./chip-tool pumpconfigurationandcontrol write lifetime-running-hours 1 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-running-hours 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write lifetime-running-hours 2 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-running-hours 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write lifetime-running-hours 3 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-running-hours 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write lifetime-energy-consumed  1 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-energy-consumed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write lifetime-energy-consumed  2 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-energy-consumed 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol write lifetime-energy-consumed  3 1 1"
      logs:
        - " "
    - command: "./chip-tool pumpconfigurationandcontrol read lifetime-energy-consumed 1 1"
      logs:
        - " "
        
